apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  slackBotToken: {{ .Values.slackBotToken | b64enc }}
  slackSigningSecret: {{ .Values.slackSigningSecret | b64enc }}
  discordBotToken: {{ .Values.discordBotToken | b64enc }}
